# Generated by Django 4.1.7 on 2023-05-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductOrderingService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Определяет, следует ли рассматривать этого пользователя как активного.Снимите этот флажок вместо удаления учетных записей.', verbose_name='active'),
        ),
    ]
