# Generated by Django 4.1.7 on 2023-05-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductOrderingService', '0003_remove_order_apartment_remove_order_building_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_order_item',
        ),
    ]
